package com.sample.app.model;

import java.util.Map;

/**
 * Represents a single step generated by the Planning Module for the Action Module to execute.
 *
 * <p>A PlanStep is a structured instruction that names one tool and provides the parameters
 * required to invoke it. The Planning Module generates exactly one PlanStep per cycle (ReAct /
 * dynamic planning); it never generates an entire workflow at once.
 *
 * @param toolName The exact tool name as registered in the ToolRegistry (e.g., "searchFlights").
 *     Must match a registered key exactly.
 * @param parameters A map of string key-value pairs passed to the tool at execution time. Keys are
 *     tool-specific (e.g., "destination", "flightId").
 * @param reasoning A brief explanation from the LLM describing why this step was chosen. Used for
 *     console output and debugging; never affects execution.
 */
public record PlanStep(String toolName, Map<String, String> parameters, String reasoning) {

  /**
   * Constructs a PlanStep with defensive copies of parameters.
   *
   * @param toolName name of the tool to invoke
   * @param parameters tool-specific parameters
   * @param reasoning LLM explanation for choosing this step
   */
  public PlanStep {
    if (toolName == null || toolName.isBlank()) {
      throw new IllegalArgumentException("PlanStep toolName must not be blank");
    }
    // Defensive immutable copy
    parameters = parameters != null ? Map.copyOf(parameters) : Map.of();
    reasoning = reasoning != null ? reasoning : "";
  }
}
