package com.sample.app.tools;

import dev.langchain4j.agent.tool.Tool;
import org.springframework.stereotype.Component;

/**
 * Simulated business metrics for TimeMachine Corp.
 * In production these would call real data sources / APIs.
 */
@Component
public class TimeTravelBusinessTools {

    @Tool("""
            Returns the current number of people who are actively time traveling at this very moment.
            Use this when the user asks how many people are currently in a time machine or on a time travel trip.
            """)
    public int currentPeopleInTimeTravel() {
        System.out.println("*** Fetching Current People in Time Travel ***");
        return 142;
    }

    @Tool("""
            Returns the total cumulative revenue generated by TimeMachine Corp from all time travel
            services in USD. Use this when the user asks about earnings, revenue, or income.
            """)
    public double totalRevenueFromTimeTravel() {
        System.out.println("*** Fetching Total Revenue From Time Travel ***");
        return 4_750_000_000.00; // $4.75 billion
    }

    @Tool("""
            Returns the total operational cost of running TimeMachine Corp's services in USD.
            This covers machine maintenance, chronite-crystal fuel, crew salaries, and temporal insurance.
            Use this when the user asks about expenses, costs, or spending.
            """)
    public double totalCost() {
        System.out.println("*** Fetching Total Operational Cost ***");
        return 1_920_000_000.00; // $1.92 billion
    }

    @Tool("""
            Returns the current market price for a standard round-trip time travel ticket in USD.
            Use this when the user asks about ticket prices, booking costs, or how much time travel costs.
            """)
    public double currentMarketPrice() {
        System.out.println("*** Fetching Current Market Price Per Ticket ***");
        return 250_000.00; // $250,000 per ticket
    }

    @Tool("""
            Returns the net profit of TimeMachine Corp in USD (total revenue minus total operational costs).
            Use this when the user asks about profit, earnings after expenses, or financial performance.
            """)
    public double netProfit() {
        System.out.println("*** Calculating Net Profit ***");
        return 4_750_000_000.00 - 1_920_000_000.00; // $2.83 billion
    }

    @Tool("""
            Returns the total number of time travel trips that have been successfully completed to date.
            Use this when the user asks how many journeys, expeditions, or time travel trips have been made.
            """)
    public int totalTripsCompleted() {
        System.out.println("*** Fetching Total Trips Completed ***");
        return 19_000;
    }

    @Tool("""
            Returns the most popular time travel destination era chosen by travelers, with booking percentage.
            Use this when the user asks about popular destinations, favourite time periods, or where people go.
            """)
    public String mostPopularDestinationEra() {
        System.out.println("*** Fetching Most Popular Destination Era ***");
        return "The Renaissance (1400–1600 AD) — 34% of all bookings";
    }

    @Tool("""
            Returns the current stock price of TimeMachine Corp (ticker: TMCORP) on the NYSE in USD.
            Use this when the user asks about the company stock price, share price, or market valuation.
            """)
    public double currentStockPrice() {
        System.out.println("*** Fetching Current TMCORP Stock Price ***");
        return 4_250.75;
    }
}
