package com.sample.documents.model;

import dev.langchain4j.model.output.structured.Description;
import java.util.List;

/**
 * Represents the structured summary generated by the AI Agent.
 *
 * <p>This model encapsulates the key sections extracted from a document, making it suitable for
 * displaying in a UI, exporting to JSON, or persisting to a database.
 */
@Description("Summary generated from a document")
public class DocumentSummary {

  @Description("Detailed summary of the document")
  private String summary;

  @Description("The major topics discussed in the document")
  private List<String> keyTopics;

  @Description("Important observations, facts, or highlights")
  private List<String> importantPoints;

  @Description("Tasks, follow-ups, or action items identified in the document")
  private List<String> actionItems;

  @Description("Overall conclusion of the document")
  private String conclusion;

  public String getSummary() {
    return summary;
  }

  public void setSummary(String summary) {
    this.summary = summary;
  }

  public List<String> getKeyTopics() {
    return keyTopics;
  }

  public void setKeyTopics(List<String> keyTopics) {
    this.keyTopics = keyTopics;
  }

  public List<String> getImportantPoints() {
    return importantPoints;
  }

  public void setImportantPoints(List<String> importantPoints) {
    this.importantPoints = importantPoints;
  }

  public List<String> getActionItems() {
    return actionItems;
  }

  public void setActionItems(List<String> actionItems) {
    this.actionItems = actionItems;
  }

  public String getConclusion() {
    return conclusion;
  }

  public void setConclusion(String conclusion) {
    this.conclusion = conclusion;
  }

  @Override
  public String toString() {

    return """
				==================================================
				Executive Summary
				==================================================
				%s

				==================================================
				Key Topics
				==================================================
				%s

				==================================================
				Important Points
				==================================================
				%s

				==================================================
				Action Items
				==================================================
				%s

				==================================================
				Conclusion
				==================================================
				%s
				"""
        .formatted(
            nullSafe(summary),
            formatList(keyTopics),
            formatList(importantPoints),
            formatList(actionItems),
            nullSafe(conclusion));
  }

  private String formatList(List<String> items) {

    if (items == null || items.isEmpty()) {
      return "N/A";
    }

    StringBuilder builder = new StringBuilder();

    for (String item : items) {
      builder.append("• ").append(item).append(System.lineSeparator());
    }

    return builder.toString().trim();
  }

  private String nullSafe(String value) {
    return value == null || value.isBlank() ? "N/A" : value;
  }
}
