package com.sample.app.service;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.Map;
import java.util.UUID;
import java.util.stream.Collectors;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.sample.app.assistant.ChatAssistant;
import com.sample.app.dto.MessageDto;
import com.sample.app.dto.ToolCallDto;

import dev.langchain4j.data.message.AiMessage;
import dev.langchain4j.data.message.ChatMessage;
import dev.langchain4j.data.message.ToolExecutionResultMessage;
import dev.langchain4j.data.message.UserMessage;
import dev.langchain4j.store.memory.chat.InMemoryChatMemoryStore;

@Service
public class ChatService {

    private static final Logger log = LoggerFactory.getLogger(ChatService.class);

    /**
     * Maps tool method names to human-readable descriptions.
     * Populated from the @Tool annotation text on each tool class.
     * Used to populate DeepEval ToolCall.description for ToolCorrectnessMetric.
     */
    private static final Map<String, String> TOOL_DESCRIPTIONS = Map.of(
        "searchTimeMachineKnowledge",
            "Searches the TimeMachine Corp official knowledge base (timemachine.pdf) for information " +
            "about time machines, time travel, safety protocols, historical destinations, and company history.",
        "currentPeopleInTimeTravel",
            "Returns the current number of people who are actively time traveling at this moment.",
        "totalRevenueFromTimeTravel",
            "Returns the total cumulative revenue generated by TimeMachine Corp from all time travel services in USD.",
        "totalCost",
            "Returns the total operational cost of running TimeMachine Corp's time travel services in USD.",
        "currentMarketPrice",
            "Returns the current market price for a standard round-trip time travel ticket in USD.",
        "netProfit",
            "Returns the net profit of TimeMachine Corp in USD (total revenue minus total operational costs).",
        "totalTripsCompleted",
            "Returns the total number of time travel trips successfully completed to date.",
        "mostPopularDestinationEra",
            "Returns the most popular time travel destination era chosen by travelers, with booking percentage.",
        "currentStockPrice",
            "Returns the current stock price of TimeMachine Corp (ticker: TMCORP) on the NYSE in USD."
    );

    @Autowired
    private ChatAssistant chatAssistant;

    @Autowired
    private InMemoryChatMemoryStore chatMemoryStore;

    @Autowired
    private ObjectMapper objectMapper;

    public MessageDto chat(List<MessageDto> messages) {
        if (messages == null || messages.isEmpty()) {
            throw new IllegalArgumentException("Messages list must not be empty");
        }

        MessageDto lastMessage = messages.get(messages.size() - 1);
        if (!"user".equalsIgnoreCase(lastMessage.getRole())) {
            throw new IllegalArgumentException("Last message must have role 'user'");
        }

        // Each request is stateless — generate a one-time memory ID
        String memoryId = UUID.randomUUID().toString();
        int historySize = messages.size() - 1;

        // Pre-populate memory with prior turns (everything except the last user message)
        if (historySize > 0) {
            List<ChatMessage> history = messages
                    .subList(0, historySize)
                    .stream()
                    .map(this::toChatMessage)
                    .collect(Collectors.toList());
            chatMemoryStore.updateMessages(memoryId, history);
        }

        try {
            String response = chatAssistant.chat(memoryId, lastMessage.getContent());

            // Inspect messages added during this request to capture tool call details
            List<ChatMessage> allMessages = chatMemoryStore.getMessages(memoryId);
            List<ToolCallDto> toolCalls = extractToolCalls(allMessages, historySize);

            return new MessageDto("assistant", response, toolCalls);
        } finally {
            // Always clean up — we don't persist history server-side
            chatMemoryStore.deleteMessages(memoryId);
        }
    }

    /**
     * Walks the messages added during the current request turn and pairs each
     * ToolExecutionRequest (inside AiMessage) with its ToolExecutionResultMessage.
     *
     * Memory layout after a tool-using turn:
     *   [history...] UserMessage → AiMessage(toolRequests) → ToolExecutionResultMessage(s) → AiMessage(text)
     */
    private List<ToolCallDto> extractToolCalls(List<ChatMessage> allMessages, int historySize) {
        if (allMessages.size() <= historySize) {
            return Collections.emptyList();
        }

        // Only inspect messages added during this request
        List<ChatMessage> newMessages = allMessages.subList(historySize, allMessages.size());

        // Map tool-call ID → result text (and try to parse typed output)
        Map<String, String> resultById = newMessages.stream()
                .filter(m -> m instanceof ToolExecutionResultMessage)
                .map(m -> (ToolExecutionResultMessage) m)
                .collect(Collectors.toMap(
                        ToolExecutionResultMessage::id,
                        ToolExecutionResultMessage::text
                ));

        List<ToolCallDto> toolCalls = new ArrayList<>();

        for (ChatMessage msg : newMessages) {
            if (msg instanceof AiMessage aiMsg && aiMsg.hasToolExecutionRequests()) {
                for (var req : aiMsg.toolExecutionRequests()) {
                    String rawOutput = resultById.getOrDefault(req.id(), "");
                    toolCalls.add(new ToolCallDto(
                            req.name(),
                            TOOL_DESCRIPTIONS.get(req.name()),
                            parseArguments(req.arguments()),
                            parseOutput(rawOutput)
                    ));
                }
            }
        }

        return toolCalls;
    }

    /**
     * Parses the tool arguments JSON string into a Map.
     * e.g. {"query":"time machine"} → Map.of("query", "time machine")
     */
    private Map<String, Object> parseArguments(String argumentsJson) {
        if (argumentsJson == null || argumentsJson.isBlank() || "{}".equals(argumentsJson.trim())) {
            return Collections.emptyMap();
        }
        try {
            return objectMapper.readValue(argumentsJson, new TypeReference<>() {});
        } catch (Exception e) {
            log.warn("Could not parse tool arguments as JSON: {}", argumentsJson);
            return Map.of("raw", argumentsJson);
        }
    }

    /**
     * Attempts to return a typed value (Number, Boolean) when the output is a
     * plain scalar; otherwise returns the raw string.
     * Matches DeepEval's ToolCall.output which accepts Any.
     */
    private Object parseOutput(String rawOutput) {
        if (rawOutput == null || rawOutput.isBlank()) {
            return rawOutput;
        }
        try {
            return objectMapper.readValue(rawOutput, Object.class);
        } catch (Exception e) {
            return rawOutput; // keep as String
        }
    }

    private ChatMessage toChatMessage(MessageDto dto) {
        return switch (dto.getRole().toLowerCase()) {
            case "user"      -> UserMessage.from(dto.getContent());
            case "assistant" -> AiMessage.from(dto.getContent());
            default          -> throw new IllegalArgumentException("Unknown role: " + dto.getRole());
        };
    }
}
