# Following details are related application
appName = "Chat Server"
appVersion = 1.23

# Application owner details
[[Owner]]
firstName = "Ram"
lastName = "Gurram"

[[Owner]]
firstName = "Sailu"
lastName = "PTR

